version: '2'

services:
  composer:
    tty: true
    image: opensourcebssd/composer:2-php7.4
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
